// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPk1-Ho4HrwwHepzy9g-hOJRRd2n9gl_o',
    appId: '1:377958781705:web:9ec1b18698ff28b8b5f9d8',
    messagingSenderId: '377958781705',
    projectId: 'taskflowapp-216ed',
    authDomain: 'taskflowapp-216ed.firebaseapp.com',
    storageBucket: 'taskflowapp-216ed.firebasestorage.app',
    measurementId: 'G-E7E08YMKR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIl4YyJL3BVvq6jhervufSXywujJy9qE',
    appId: '1:377958781705:android:90f28c9f73d835d2b5f9d8',
    messagingSenderId: '377958781705',
    projectId: 'taskflowapp-216ed',
    storageBucket: 'taskflowapp-216ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSBtAhmhv5paW8Gve9peKCOFX0sumhuFY',
    appId: '1:377958781705:ios:e21816ed57134084b5f9d8',
    messagingSenderId: '377958781705',
    projectId: 'taskflowapp-216ed',
    storageBucket: 'taskflowapp-216ed.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSBtAhmhv5paW8Gve9peKCOFX0sumhuFY',
    appId: '1:377958781705:ios:e21816ed57134084b5f9d8',
    messagingSenderId: '377958781705',
    projectId: 'taskflowapp-216ed',
    storageBucket: 'taskflowapp-216ed.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPk1-Ho4HrwwHepzy9g-hOJRRd2n9gl_o',
    appId: '1:377958781705:web:0239521d4a052115b5f9d8',
    messagingSenderId: '377958781705',
    projectId: 'taskflowapp-216ed',
    authDomain: 'taskflowapp-216ed.firebaseapp.com',
    storageBucket: 'taskflowapp-216ed.firebasestorage.app',
    measurementId: 'G-REBYLCLJWE',
  );
}
